### ISSUE TITLE
Crashes With Latest Forge

### ISSUE THREAD

**Issue by ghost** [thebrightspark/SparksHammers#33]
game won't start on Forge 2363

**Comment by SDUBZ** [comment]
crash on load
Forge: 1.12-2368
SH: 1.12-1.6.5.1


[crash-2017-06-26_17.01.40-client.txt](https://github.com/thebrightspark/SparksHammers/files/1101240/crash-2017-06-26_17.01.40-client.txt)

**Comment by ghost** [comment]
[crash-2017-07-02_15.00.50-client.txt](https://github.com/thebrightspark/SparksHammers/files/1117771/crash-2017-07-02_15.00.50-client.txt)
hello...anyone hear me...

**Comment by thebrightspark** [comment]
Well you're using a Forge version later than what the mod is currently built for, and Forge builds are currently unstable atm. You shouldn't really be even using them yet. I'll updated and fix it when I have time.

**Comment by thebrightspark** [comment]
This should now be fixed as I've updated to the currently most recent Forge version in commit https://github.com/thebrightspark/SparksHammers/commit/fe0260b0729f584797f04868c05bbc4814554e0a

**Comment by MoonCutter2B** [comment]
Sorry, but it still crashes for me. 1.6.6 with forge 2402 - will test with forge 2405 soonish
Edit: 2405 din't help :(
